package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLab<M extends BaseLab<M>> extends Model<M> implements IBean {

	public void setLabId(java.lang.Integer labId) {
		set("lab_id", labId);
	}
	
	public java.lang.Integer getLabId() {
		return getInt("lab_id");
	}

	public void setLabName(java.lang.String labName) {
		set("lab_name", labName);
	}
	
	public java.lang.String getLabName() {
		return getStr("lab_name");
	}

	public void setLabPlace(java.lang.String labPlace) {
		set("lab_place", labPlace);
	}
	
	public java.lang.String getLabPlace() {
		return getStr("lab_place");
	}

	public void setLabIntro(java.lang.String labIntro) {
		set("lab_intro", labIntro);
	}
	
	public java.lang.String getLabIntro() {
		return getStr("lab_intro");
	}

	public void setLabWeb(java.lang.String labWeb) {
		set("lab_web", labWeb);
	}
	
	public java.lang.String getLabWeb() {
		return getStr("lab_web");
	}

}
